# Generated by Django 5.1.6 on 2025-03-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_custompage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomPage',
        ),
    ]
