# Generated by Django 5.1.8 on 2025-04-10 13:16
import json
from django.core.serializers.json import DjangoJSONEncoder
import wagtail.blocks
import wagtail.fields
from django.db import migrations


def convert_to_streamfield(apps, schema_editor):
    BlogPage = apps.get_model('blog', 'BlogPage')
    for page in BlogPage.objects.all():
        page.body = json.dumps(
            [{"type": "rich_text", "value": page.body}],
            cls=DjangoJSONEncoder
        )
        page.save()


def convert_to_richtext(apps, schema_editor):
    BlogPage = apps.get_model("demo", "BlogPage")
    for page in BlogPage.objects.all():
        if page.body:
            stream = json.loads(page.body)
            page.body = "".join([
                child["value"] for child in stream
                if child["type"] == "rich_text"
            ])
            page.save()


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0007_blogchannel_blogtagindexpage_and_more'),
    ]

    operations = [
        migrations.RunPython(
            convert_to_streamfield,
            convert_to_richtext,
        ),

        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('markdown', 1)], block_lookup={0: (
            'wagtail.blocks.RichTextBlock', (), {'blank': True,
                                                 'features': ['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'embed',
                                                              'image', 'link', 'document-link', 'code', 'blockquote'],
                                                 'label': 'テキスト'}), 1: (
            'wagtailmarkdown.blocks.MarkdownBlock', (), {'blank': True, 'label': 'マークダウン'})}),
        ),
    ]
