# Generated by Django 5.1.8 on 2025-04-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='primary_tag',
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=models.CharField(max_length=16),
        ),
        migrations.DeleteModel(
            name='BlogTagIndexPage',
        ),
    ]
