# Generated by Django 5.1.8 on 2025-04-24 14:59

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('markdown', 1), ('image', 4), ('code', 7)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'features': ['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'embed', 'image', 'link', 'document-link', 'code', 'blockquote'], 'label': 'テキスト'}), 1: ('wagtailmarkdown.blocks.MarkdownBlock', (), {'blank': True, 'label': 'マークダウン'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': '画像', 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'キャプション', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3)]], {'blank': True, 'label': '画像'}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bash', 'Bash/Shell'), ('css', 'CSS'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('sql', 'SQL')], 'help_text': 'Coding language', 'identifier': 'language', 'label': 'Language'}), 6: ('wagtail.blocks.TextBlock', (), {'identifier': 'code', 'label': 'Code'}), 7: ('wagtail.blocks.StructBlock', [[('language', 5), ('code', 6)]], {'blank': True, 'default_language': 'python', 'label': 'コード'})}),
        ),
    ]
